title: Brandon Johnson
logo: /assets/self.png
decription: 
### ğŸ” Focus
- Cyber security
- Frontend/backend development
- Developing a lexicon of programming languages  
- Program and script development
---
### ğŸ“„ Experience
- 15+ Years experience with such Adobe programs as;<br>
  Photoshop, Flash, After Effects, Dream Weaver, and Light Room
- 10+ Experience with HTML, Java, JavaScript, Python, and Linux 
- 5+ Years Cyber Security
show_downloads: false
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
